version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CRON_SECRET_KEY=${CRON_SECRET_KEY}
      - TEST_AUTH_TOKEN=${TEST_AUTH_TOKEN} 